# Generated by Django 5.1.4 on 2025-08-17 06:48

import django.db.models.deletion
import django_ckeditor_5.fields
import products.storage
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoatCategory',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('category_name', models.CharField(help_text='Например: Yamaha, Mercury, Suzuki', max_length=200, verbose_name='Название категории лодок')),
                ('slug', models.SlugField(help_text='Автоматически генерируется из названия', max_length=255, unique=True, verbose_name='URL-адрес')),
                ('category_image', models.ImageField(blank=True, help_text='Логотип бренда лодки. Рекомендуемый размер: 400x300px', null=True, storage=products.storage.OverwriteStorage(), upload_to='boat_categories', verbose_name='Изображение категории')),
                ('description', django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Подробное описание категории лодок', null=True, verbose_name='Описание категории')),
                ('page_title', models.CharField(blank=True, help_text='SEO заголовок для страницы категории', max_length=200, null=True, verbose_name='Заголовок страницы (Title)')),
                ('meta_description', models.TextField(blank=True, help_text='SEO описание для поисковых систем', null=True, verbose_name='Meta Description')),
                ('is_active', models.BooleanField(default=True, help_text='Показывать категорию на сайте', verbose_name='Активная категория')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Чем меньше число, тем выше в списке', verbose_name='Порядок отображения')),
            ],
            options={
                'verbose_name': '🛥️ Категория лодок',
                'verbose_name_plural': '🛥️ Категории лодок',
                'ordering': ['display_order', 'category_name'],
            },
        ),
        migrations.CreateModel(
            name='BoatProduct',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('product_name', models.CharField(help_text='Например: Коврик EVA для Yamaha F150', max_length=200, verbose_name='Название товара')),
                ('slug', models.SlugField(help_text='Автоматически генерируется из названия', max_length=255, unique=True, verbose_name='URL-адрес')),
                ('price', models.IntegerField(blank=True, default=0, help_text='Цена в рублях (целое число)', null=True, verbose_name='Базовая цена')),
                ('product_desription', django_ckeditor_5.fields.CKEditor5Field(help_text='Подробное описание товара с возможностью форматирования', verbose_name='Описание товара')),
                ('newest_product', models.BooleanField(default=False, verbose_name='Новый товар')),
                ('product_sku', models.CharField(blank=True, help_text='Уникальный код товара для импорта и учета', max_length=50, null=True, unique=True, verbose_name='Артикул товара')),
                ('boat_mat_length', models.PositiveIntegerField(blank=True, help_text='Длина коврика для лодки в сантиметрах', null=True, verbose_name='Длина коврика (см)')),
                ('boat_mat_width', models.PositiveIntegerField(blank=True, help_text='Ширина коврика для лодки в сантиметрах', null=True, verbose_name='Ширина коврика (см)')),
                ('page_title', models.CharField(blank=True, help_text='SEO заголовок для страницы товара', max_length=200, null=True, verbose_name='Заголовок страницы (Title)')),
                ('meta_description', models.TextField(blank=True, help_text='SEO описание для поисковых систем', null=True, verbose_name='Meta Description')),
                ('category', models.ForeignKey(help_text='Выберите бренд лодки', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='boats.boatcategory', verbose_name='Категория лодки')),
            ],
            options={
                'verbose_name': '🛥️ Товар (лодка)',
                'verbose_name_plural': '🛥️ Товары (лодки)',
                'ordering': ['-created_at', 'product_name'],
            },
        ),
        migrations.CreateModel(
            name='BoatProductImage',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(help_text='Фото лодочного коврика. Рекомендуемый размер: 800x600px', storage=products.storage.OverwriteStorage(), upload_to='boat_products', verbose_name='Изображение')),
                ('alt_text', models.CharField(blank=True, help_text='Описание изображения для SEO и доступности', max_length=255, verbose_name='Alt текст')),
                ('is_main', models.BooleanField(default=False, help_text='Основное изображение товара для каталога', verbose_name='Главное изображение')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Порядок в галерее (меньше число = выше)', verbose_name='Порядок отображения')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='boats.boatproduct', verbose_name='Товар лодки')),
            ],
            options={
                'verbose_name': '🖼️ Изображение лодочного товара',
                'verbose_name_plural': '🖼️ Изображения лодочных товаров',
                'ordering': ['display_order', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='boatproduct',
            index=models.Index(fields=['category', 'newest_product'], name='boats_boatp_categor_428f73_idx'),
        ),
        migrations.AddIndex(
            model_name='boatproduct',
            index=models.Index(fields=['slug'], name='boats_boatp_slug_5d8103_idx'),
        ),
        migrations.AddIndex(
            model_name='boatproduct',
            index=models.Index(fields=['product_sku'], name='boats_boatp_product_627e78_idx'),
        ),
    ]
