# Generated by Django 5.1.12 on 2025-09-17 05:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('products', '0003_alter_wishlist_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Уникальный ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('object_id', models.UUIDField()),
                ('stars', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='Оценка')),
                ('content', models.TextField(verbose_name='Содержание отзыва')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('is_approved', models.BooleanField(default=False, help_text='Отзыв прошел модерацию и виден всем пользователям', verbose_name='Одобрен')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('dislikes', models.ManyToManyField(blank=True, related_name='disliked_reviews', to=settings.AUTH_USER_MODEL, verbose_name='Дизлайки')),
                ('likes', models.ManyToManyField(blank=True, related_name='liked_reviews', to=settings.AUTH_USER_MODEL, verbose_name='Лайки')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'db_table': 'products_productreview',
                'ordering': ['-date_added'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='products_pr_content_f09599_idx'), models.Index(fields=['is_approved', 'date_added'], name='products_pr_is_appr_7467fe_idx'), models.Index(fields=['user', 'date_added'], name='products_pr_user_id_699347_idx')],
            },
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Уникальный ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('object_id', models.UUIDField()),
                ('has_podpyatnik', models.BooleanField(default=False, help_text='Применимо только к автомобильным коврикам', verbose_name='С подпятником')),
                ('added_on', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('border_color', models.ForeignKey(blank=True, limit_choices_to={'color_type': 'border'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wishlist_border', to='products.color', verbose_name='Цвет окантовки')),
                ('carpet_color', models.ForeignKey(blank=True, limit_choices_to={'color_type': 'carpet'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wishlist_carpet', to='products.color', verbose_name='Цвет коврика')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('kit_variant', models.ForeignKey(blank=True, help_text='Применимо только к автомобильным коврикам', null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.kitvariant', verbose_name='Комплектация')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Избранное',
                'verbose_name_plural': 'Избранное',
                'db_table': 'products_wishlist',
                'ordering': ['-added_on'],
                'indexes': [models.Index(fields=['user', 'added_on'], name='products_wi_user_id_af461e_idx'), models.Index(fields=['content_type', 'object_id'], name='products_wi_content_5c2779_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'content_type', 'object_id'), name='unique_user_product_wishlist')],
            },
        ),
    ]
