# Generated by Django 5.1.4 on 2025-08-11 10:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("common", "__first__"),
        ("contenttypes", "0002_remove_content_type_name"),
        ("products", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Cart",
            fields=[
                (
                    "uid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
                ("session_id", models.CharField(blank=True, max_length=50, null=True)),
                ("is_paid", models.BooleanField(default=False)),
                (
                    "coupon",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="products.coupon",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cart",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Корзина",
                "verbose_name_plural": "Корзины",
            },
        ),
        migrations.CreateModel(
            name="CartItem",
            fields=[
                (
                    "uid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
                ("object_id", models.UUIDField()),
                ("quantity", models.IntegerField(default=1)),
                ("has_podpyatnik", models.BooleanField(default=False)),
                (
                    "border_color",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cart_items_border",
                        to="common.color",
                    ),
                ),
                (
                    "carpet_color",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cart_items_carpet",
                        to="common.color",
                    ),
                ),
                (
                    "cart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cart_items",
                        to="accounts.cart",
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "kit_variant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="products.kitvariant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Товар в корзине",
                "verbose_name_plural": "Товары в корзине",
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "uid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "customer_name",
                    models.CharField(max_length=100, verbose_name="Имя клиента"),
                ),
                (
                    "customer_phone",
                    models.CharField(max_length=20, verbose_name="Контактный телефон"),
                ),
                (
                    "customer_email",
                    models.EmailField(max_length=254, verbose_name="Email клиента"),
                ),
                (
                    "customer_city",
                    models.CharField(max_length=100, verbose_name="Город клиента"),
                ),
                (
                    "delivery_method",
                    models.CharField(
                        choices=[
                            ("pickup", "🏪 Самовывоз"),
                            ("europochta", "📦Европочта"),
                            ("belpochta", "📮Белпочта"),
                            ("yandex", "🚚 Яндекс курьер по Минску"),
                        ],
                        default="pickup",
                        max_length=20,
                        verbose_name="Способ доставки",
                    ),
                ),
                (
                    "shipping_address",
                    models.TextField(
                        blank=True, null=True, verbose_name="Адрес доставки"
                    ),
                ),
                (
                    "order_total_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Сумма заказа"
                    ),
                ),
                (
                    "grand_total",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Итого к оплате"
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("pending", "Ожидает оплаты"),
                            ("paid", "Оплачен"),
                            ("cancelled", "Отменен"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Статус оплаты",
                    ),
                ),
                (
                    "payment_mode",
                    models.CharField(
                        choices=[("cash", "Наличные"), ("card", "Банковская карта")],
                        default="cash",
                        max_length=20,
                    ),
                ),
                (
                    "order_notes",
                    models.TextField(
                        blank=True, null=True, verbose_name="Комментарии к заказу"
                    ),
                ),
                (
                    "order_id",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Номер заказа"
                    ),
                ),
                (
                    "order_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата заказа"),
                ),
                (
                    "coupon",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="products.coupon",
                        verbose_name="Купон",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Заказ",
                "verbose_name_plural": "Заказы",
                "ordering": ["-order_date"],
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "uid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
                ("object_id", models.UUIDField(null=True)),
                ("quantity", models.PositiveIntegerField(default=1)),
                (
                    "product_price",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                ("has_podpyatnik", models.BooleanField(default=False)),
                (
                    "border_color",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="order_items_border",
                        to="common.color",
                    ),
                ),
                (
                    "carpet_color",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="order_items_carpet",
                        to="common.color",
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "kit_variant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="products.kitvariant",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order_items",
                        to="accounts.order",
                    ),
                ),
            ],
            options={
                "verbose_name": "Товар в заказе",
                "verbose_name_plural": "Товары в заказе",
            },
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "uid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
                ("is_email_verified", models.BooleanField(default=False)),
                (
                    "email_token",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "profile_image",
                    models.ImageField(blank=True, null=True, upload_to="profile"),
                ),
                ("bio", models.TextField(blank=True, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Профиль пользователя",
                "verbose_name_plural": "Профили пользователей",
            },
        ),
    ]
