# Generated by Django 5.1.4 on 2025-05-26 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='color_variant',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='color_variant',
        ),
    ]
