# Generated by Django 5.1.4 on 2025-08-17 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('products', '0002_add_boats_support'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='tracking_code',
        ),
        migrations.AlterField(
            model_name='order',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.coupon', verbose_name='Купон'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_method',
            field=models.CharField(choices=[('pickup', '🏪 Самовывоз'), ('europochta', '📦Европочта'), ('belpochta', '📮Белпочта'), ('yandex', '🚚 Яндекс курьер по Минску')], default='pickup', max_length=20, verbose_name='Способ доставки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='grand_total',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Итого к оплате'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата заказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(max_length=20, unique=True, verbose_name='Номер заказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_notes',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарии к заказу'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_total_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма заказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_mode',
            field=models.CharField(choices=[('cash', 'Наличные'), ('card', 'Банковская карта')], default='cash', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Ожидает оплаты'), ('paid', 'Оплачен'), ('cancelled', 'Отменен')], default='pending', max_length=20, verbose_name='Статус оплаты'),
        ),
    ]
