# Generated by Django 5.1.4 on 2025-05-28 20:13
# ✅ ИСПРАВЛЕНО: Заменен импорт django_summernote на ckeditor

import django.db.models.deletion
# ❌ СТАРЫЙ: import django_summernote.fields
import ckeditor.fields  # ✅ НОВЫЙ ИМПОРТ
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название категории')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='URL-адрес')),
                ('description', models.TextField(blank=True, help_text='Описание для SEO и отображения на странице категории', verbose_name='Описание категории')),
                ('image', models.ImageField(blank=True, help_text='Рекомендуемый размер: 800x400 px', null=True, upload_to='blog/categories/', verbose_name='Изображение категории')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Чем меньше число, тем выше в списке', verbose_name='Порядок сортировки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Категория статей',
                'verbose_name_plural': 'Категории статей',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок статьи')),
                ('slug', models.SlugField(help_text='Автоматически генерируется из заголовка с .html в конце', max_length=255, unique=True, verbose_name='URL-адрес')),
                ('featured_image', models.ImageField(help_text='Рекомендуемый размер: 1200x600 px', upload_to='blog/articles/', verbose_name='Главное изображение')),
                # ✅ ИСПРАВЛЕНО: Заменено django_summernote.fields на ckeditor.fields
                ('excerpt', ckeditor.fields.RichTextField(help_text='Краткое описание для карточки статьи (анонс)', verbose_name='Краткое описание')),
                ('content', ckeditor.fields.RichTextField(help_text='Полное содержание статьи с форматированием', verbose_name='Содержание статьи')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='Просмотры')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('published_at', models.DateTimeField(blank=True, help_text='Можно установить дату публикации в будущем', null=True, verbose_name='Дата публикации')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='blog.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
                'ordering': ['-published_at', '-created_at'],
                'indexes': [models.Index(fields=['slug'], name='blog_articl_slug_cc8df7_idx'), models.Index(fields=['is_published', '-published_at'], name='blog_articl_is_publ_5425cf_idx')],
            },
        ),
    ]

# 🔧 ИЗМЕНЕНИЯ:
# ✅ ЗАМЕНЕН: import django_summernote.fields → import ckeditor.fields
# ✅ ЗАМЕНЕНО: django_summernote.fields.SummernoteTextField → ckeditor.fields.RichTextField
# ✅ СОХРАНЕНО: Все остальные настройки полей без изменений