# Generated by Django 5.1.4 on 2025-08-11 10:36

import django.db.models.deletion
import django_ckeditor_5.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Banner",
            fields=[
                (
                    "uid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
                ("title", models.CharField(max_length=200, verbose_name="Заголовок")),
                (
                    "subtitle",
                    models.CharField(
                        blank=True,
                        max_length=300,
                        null=True,
                        verbose_name="Подзаголовок",
                    ),
                ),
                (
                    "image",
                    models.ImageField(upload_to="banners/", verbose_name="Изображение"),
                ),
                ("link", models.URLField(blank=True, null=True, verbose_name="Ссылка")),
                (
                    "button_text",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Текст кнопки",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Порядок отображения"
                    ),
                ),
            ],
            options={
                "verbose_name": "Баннер",
                "verbose_name_plural": "Баннеры",
                "ordering": ["order", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CompanyDescription",
            fields=[
                (
                    "uid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "title",
                    models.CharField(
                        default="О нашей компании",
                        help_text="Заголовок блока описания компании",
                        max_length=200,
                        verbose_name="Заголовок",
                    ),
                ),
                (
                    "content",
                    django_ckeditor_5.fields.CKEditor5Field(
                        help_text="Текст с описанием компании, продукции, преимуществ",
                        verbose_name="Описание компании",
                    ),
                ),
            ],
            options={
                "verbose_name": "Описание компании",
                "verbose_name_plural": "Описание компании",
            },
        ),
        migrations.CreateModel(
            name="ContactInfo",
            fields=[
                (
                    "uid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
                ("phone", models.CharField(max_length=20, verbose_name="Телефон")),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                ("address", models.TextField(verbose_name="Физический адрес")),
                (
                    "working_hours",
                    models.CharField(max_length=100, verbose_name="Часы работы"),
                ),
                (
                    "telegram",
                    models.URLField(blank=True, null=True, verbose_name="Telegram"),
                ),
                (
                    "instagram",
                    models.URLField(blank=True, null=True, verbose_name="Instagram"),
                ),
                (
                    "facebook",
                    models.URLField(blank=True, null=True, verbose_name="Facebook"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активна"),
                ),
            ],
            options={
                "verbose_name": "Контактная информация",
                "verbose_name_plural": "Контактная информация",
            },
        ),
        migrations.CreateModel(
            name="FAQ",
            fields=[
                (
                    "uid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
                ("question", models.CharField(max_length=255, verbose_name="Вопрос")),
                ("answer", models.TextField(verbose_name="Ответ")),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Порядок отображения"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
            ],
            options={
                "verbose_name": "Частый вопрос",
                "verbose_name_plural": "Частые вопросы",
                "ordering": ["order", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="HeroSection",
            fields=[
                (
                    "uid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "title",
                    models.CharField(
                        default="EVA коврики в Минске",
                        max_length=200,
                        verbose_name="Заголовок",
                    ),
                ),
                (
                    "subtitle",
                    models.CharField(
                        default="Премиум коврики из экологически чистого материала",
                        max_length=300,
                        verbose_name="Подзаголовок",
                    ),
                ),
                (
                    "video",
                    models.FileField(
                        blank=True,
                        help_text="MP4 файл для фонового видео (рекомендуется до 10MB)",
                        null=True,
                        upload_to="hero_videos/",
                        verbose_name="Фоновое видео",
                    ),
                ),
                (
                    "fallback_image",
                    models.ImageField(
                        blank=True,
                        help_text="Отображается если видео не загружается",
                        null=True,
                        upload_to="hero_images/",
                        verbose_name="Изображение-заглушка",
                    ),
                ),
                (
                    "button_text",
                    models.CharField(
                        default="Смотреть каталог",
                        max_length=50,
                        verbose_name="Текст кнопки",
                    ),
                ),
                (
                    "button_link",
                    models.URLField(default="/products/", verbose_name="Ссылка кнопки"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активна"),
                ),
            ],
            options={
                "verbose_name": "Hero-секция",
                "verbose_name_plural": "Hero-секции",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                (
                    "uid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
                ("name", models.CharField(max_length=100, verbose_name="Имя клиента")),
                (
                    "position",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Должность/город",
                    ),
                ),
                ("text", models.TextField(verbose_name="Текст отзыва")),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="testimonials/",
                        verbose_name="Фото",
                    ),
                ),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)],
                        default=5,
                        verbose_name="Оценка",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                (
                    "featured",
                    models.BooleanField(default=False, verbose_name="Рекомендуемый"),
                ),
            ],
            options={
                "verbose_name": "Отзыв клиента",
                "verbose_name_plural": "Отзывы клиентов",
                "ordering": ["-featured", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="HeroAdvantage",
            fields=[
                (
                    "uid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "icon_file",
                    models.ImageField(
                        blank=True,
                        help_text="SVG или PNG файл (рекомендуется 64x64px)",
                        null=True,
                        upload_to="hero_icons/",
                        verbose_name="Файл иконки",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Альтернатива файлу - эмодзи или текст",
                        max_length=10,
                        null=True,
                        verbose_name="Эмодзи иконка",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=100, verbose_name="Заголовок преимущества"
                    ),
                ),
                (
                    "description",
                    models.CharField(max_length=200, verbose_name="Описание"),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Порядок отображения"
                    ),
                ),
                (
                    "hero_section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="advantages",
                        to="home.herosection",
                        verbose_name="Hero-секция",
                    ),
                ),
            ],
            options={
                "verbose_name": "Преимущество Hero-секции",
                "verbose_name_plural": "Преимущества Hero-секции",
                "ordering": ["order", "created_at"],
            },
        ),
    ]
