# Generated by Django 5.1.4 on 2025-06-26 08:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(default='EVA коврики в Минске', max_length=200, verbose_name='Заголовок')),
                ('subtitle', models.CharField(default='уют, комфорт, чистота в вашем автомобиле', max_length=300, verbose_name='Подзаголовок')),
                ('video', models.FileField(help_text='Видео для фона hero-секции (рекомендуемый формат: MP4)', upload_to='videos/', verbose_name='Фоновое видео')),
                ('fallback_image', models.ImageField(blank=True, help_text='Изображение для устройств, не поддерживающих видео', null=True, upload_to='hero/', verbose_name='Изображение-заглушка')),
                ('button_text', models.CharField(default='ЗАКАЗАТЬ', max_length=50, verbose_name='Текст кнопки')),
                ('button_link', models.CharField(default='#catalog-section', help_text='Якорь или URL для кнопки (например: #catalog-section)', max_length=100, verbose_name='Ссылка кнопки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Hero-секция',
                'verbose_name_plural': 'Hero-секции',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HeroAdvantage',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('icon', models.CharField(choices=[('🚚', '🚚 Доставка'), ('🧵', '🧵 Материалы'), ('🚗', '🚗 Совместимость'), ('🧽', '🧽 Чистота'), ('⚡', '⚡ Скорость'), ('💎', '💎 Качество'), ('🛡️', '🛡️ Гарантия'), ('💰', '💰 Цена')], default='🚚', max_length=10, verbose_name='Иконка')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('description', models.CharField(max_length=200, verbose_name='Описание')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок отображения')),
                ('hero_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advantages', to='home.herosection', verbose_name='Hero-секция')),
            ],
            options={
                'verbose_name': 'Преимущество hero-секции',
                'verbose_name_plural': 'Преимущества hero-секции',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
