# Generated by Django 5.1.4 on 2025-06-26 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_herosection_heroadvantage'),
    ]

    operations = [
        migrations.AddField(
            model_name='heroadvantage',
            name='icon_file',
            field=models.FileField(blank=True, help_text='Загрузите SVG файл для иконки (рекомендуется)', null=True, upload_to='hero/icons/', verbose_name='SVG иконка'),
        ),
        migrations.AlterField(
            model_name='heroadvantage',
            name='icon',
            field=models.CharField(choices=[('🚚', '🚚 Доставка'), ('🧵', '🧵 Материалы'), ('🚗', '🚗 Совместимость'), ('🧽', '🧽 Чистота'), ('⚡', '⚡ Скорость'), ('💎', '💎 Качество'), ('🛡️', '🛡️ Гарантия'), ('💰', '💰 Цена')], default='🚚', help_text='Используется, если SVG иконка не загружена', max_length=10, verbose_name='Эмодзи (запасной вариант)'),
        ),
    ]
