# Generated by Django 5.1.4 on 2025-06-26 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_heroadvantage_icon_file_alter_heroadvantage_icon'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='heroadvantage',
            options={'ordering': ['hero_section', 'order', 'created_at'], 'verbose_name': 'Преимущество hero-секции', 'verbose_name_plural': 'Преимущества hero-секций'},
        ),
        migrations.AlterModelOptions(
            name='herosection',
            options={'ordering': ['order', '-created_at'], 'verbose_name': 'Hero-секция', 'verbose_name_plural': 'Hero-секции'},
        ),
        migrations.RemoveField(
            model_name='heroadvantage',
            name='icon_file',
        ),
        migrations.AddField(
            model_name='heroadvantage',
            name='emoji',
            field=models.CharField(blank=True, help_text='Эмодзи как запасной вариант если иконка не загружается', max_length=10, null=True, verbose_name='Эмодзи (fallback)'),
        ),
        migrations.AddField(
            model_name='heroadvantage',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активно'),
        ),
        migrations.AddField(
            model_name='herosection',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок отображения'),
        ),
        migrations.AlterField(
            model_name='heroadvantage',
            name='description',
            field=models.TextField(help_text='Подробное описание преимущества', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='heroadvantage',
            name='hero_section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advantages', to='home.herosection', verbose_name='Hero секция'),
        ),
        migrations.AlterField(
            model_name='heroadvantage',
            name='icon',
            field=models.FileField(help_text='SVG или PNG файл для иконки преимущества', upload_to='hero/icons/', verbose_name='SVG иконка'),
        ),
        migrations.AlterField(
            model_name='heroadvantage',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Чем меньше число, тем левее блок', verbose_name='Порядок отображения'),
        ),
        migrations.AlterField(
            model_name='heroadvantage',
            name='title',
            field=models.CharField(help_text='Краткое название преимущества', max_length=100, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='button_link',
            field=models.CharField(default='#catalog-section', help_text='URL или якорь (#catalog-section)', max_length=200, verbose_name='Ссылка кнопки'),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='fallback_image',
            field=models.ImageField(blank=True, help_text='Показывается если видео не загружается', null=True, upload_to='hero/images/', verbose_name='Изображение-заглушка'),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='subtitle',
            field=models.CharField(default='уют, комфорт, чистота в вашем автомобиле', help_text='Описание под заголовком', max_length=300, verbose_name='Подзаголовок'),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='title',
            field=models.CharField(default='EVA коврики в Минске', help_text='Основной заголовок hero секции', max_length=200, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='video',
            field=models.FileField(blank=True, help_text='MP4 файл для фона hero секции', null=True, upload_to='hero/videos/', verbose_name='Фоновое видео'),
        ),
    ]
