# Generated by Django 5.1.4 on 2025-06-26 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_heroadvantage_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='heroadvantage',
            options={'ordering': ['order', 'created_at'], 'verbose_name': 'Преимущество hero-секции', 'verbose_name_plural': 'Преимущества hero-секции'},
        ),
        migrations.AlterModelOptions(
            name='herosection',
            options={'ordering': ['-created_at'], 'verbose_name': 'Hero-секция', 'verbose_name_plural': 'Hero-секции'},
        ),
        migrations.RemoveField(
            model_name='heroadvantage',
            name='emoji',
        ),
        migrations.RemoveField(
            model_name='heroadvantage',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='herosection',
            name='order',
        ),
        migrations.AddField(
            model_name='heroadvantage',
            name='icon_file',
            field=models.FileField(blank=True, help_text='Загрузите SVG файл для иконки (рекомендуется)', null=True, upload_to='hero/icons/', verbose_name='SVG иконка'),
        ),
        migrations.AlterField(
            model_name='heroadvantage',
            name='description',
            field=models.CharField(max_length=200, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='heroadvantage',
            name='hero_section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advantages', to='home.herosection', verbose_name='Hero-секция'),
        ),
        migrations.AlterField(
            model_name='heroadvantage',
            name='icon',
            field=models.CharField(choices=[('🚚', '🚚 Доставка'), ('🧵', '🧵 Материалы'), ('🚗', '🚗 Совместимость'), ('🧽', '🧽 Чистота'), ('⚡', '⚡ Скорость'), ('💎', '💎 Качество'), ('🛡️', '🛡️ Гарантия'), ('💰', '💰 Цена')], default='🚚', help_text='Используется, если SVG иконка не загружена', max_length=10, verbose_name='Эмодзи (запасной вариант)'),
        ),
        migrations.AlterField(
            model_name='heroadvantage',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок отображения'),
        ),
        migrations.AlterField(
            model_name='heroadvantage',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='button_link',
            field=models.CharField(default='#catalog-section', help_text='Якорь или URL для кнопки (например: #catalog-section)', max_length=100, verbose_name='Ссылка кнопки'),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='fallback_image',
            field=models.ImageField(blank=True, help_text='Изображение для устройств, не поддерживающих видео', null=True, upload_to='hero/', verbose_name='Изображение-заглушка'),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='subtitle',
            field=models.CharField(default='уют, комфорт, чистота в вашем автомобиле', max_length=300, verbose_name='Подзаголовок'),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='title',
            field=models.CharField(default='EVA коврики в Минске', max_length=200, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='video',
            field=models.FileField(help_text='Видео для фона hero-секции (рекомендуемый формат: MP4)', upload_to='videos/', verbose_name='Фоновое видео'),
        ),
    ]
