# Generated by Django 5.1.4 on 2025-07-14 08:19

import django_ckeditor_5.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_heroadvantage_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoSection',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(help_text='Основной заголовок информационного блока', max_length=200, verbose_name='Заголовок блока')),
                ('content', django_ckeditor_5.fields.CKEditor5Field(help_text='Описание компании или другая информация с возможностью форматирования', verbose_name='Содержимое блока')),
                ('icon_file', models.ImageField(blank=True, help_text='SVG, PNG или JPG файл для иконки (рекомендуется 64x64px)', null=True, upload_to='info_sections/icons/', verbose_name='Файл иконки')),
                ('icon_text', models.CharField(blank=True, help_text='Эмодзи или короткий текст как альтернатива файлу (например: 🏢, ⭐)', max_length=20, null=True, verbose_name='Текстовая иконка')),
                ('is_active', models.BooleanField(default=True, help_text='Отображать блок на сайте', verbose_name='Активен')),
                ('order', models.PositiveIntegerField(default=0, help_text='Чем меньше число, тем выше в списке (0 = первый)', verbose_name='Порядок отображения')),
                ('show_on_homepage', models.BooleanField(default=True, help_text='Отображать этот блок на главной странице', verbose_name='Показывать на главной')),
            ],
            options={
                'verbose_name': 'Информационный блок',
                'verbose_name_plural': 'Информационные блоки',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='heroadvantage',
            options={'ordering': ['order', 'created_at'], 'verbose_name': 'Преимущество Hero-секции', 'verbose_name_plural': 'Преимущества Hero-секции'},
        ),
        migrations.AlterField(
            model_name='heroadvantage',
            name='icon',
            field=models.CharField(blank=True, help_text='Альтернатива файлу - эмодзи или текст', max_length=10, null=True, verbose_name='Эмодзи иконка'),
        ),
        migrations.AlterField(
            model_name='heroadvantage',
            name='icon_file',
            field=models.ImageField(blank=True, help_text='SVG или PNG файл (рекомендуется 64x64px)', null=True, upload_to='hero_icons/', verbose_name='Файл иконки'),
        ),
        migrations.AlterField(
            model_name='heroadvantage',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Заголовок преимущества'),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='button_link',
            field=models.URLField(default='/products/', verbose_name='Ссылка кнопки'),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='button_text',
            field=models.CharField(default='Смотреть каталог', max_length=50, verbose_name='Текст кнопки'),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='fallback_image',
            field=models.ImageField(blank=True, help_text='Отображается если видео не загружается', null=True, upload_to='hero_images/', verbose_name='Изображение-заглушка'),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='subtitle',
            field=models.CharField(default='Премиум коврики из экологически чистого материала', max_length=300, verbose_name='Подзаголовок'),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='video',
            field=models.FileField(blank=True, help_text='MP4 файл для фонового видео (рекомендуется до 10MB)', null=True, upload_to='hero_videos/', verbose_name='Фоновое видео'),
        ),
    ]
