# Generated by Django 5.1.4 on 2025-07-14 08:40

import django_ckeditor_5.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_add_infosection_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyDescription',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(default='О нашей компании', help_text='Заголовок блока описания компании', max_length=200, verbose_name='Заголовок')),
                ('content', django_ckeditor_5.fields.CKEditor5Field(help_text='Текст с описанием компании, продукции, преимуществ', verbose_name='Описание компании')),
            ],
            options={
                'verbose_name': 'Описание компании',
                'verbose_name_plural': 'Описание компании',
            },
        ),
        migrations.DeleteModel(
            name='InfoSection',
        ),
    ]
