# Generated by Django 5.1.4 on 2025-08-11 10:36

import django.db.models.deletion
import django_ckeditor_5.fields
import products.storage
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "uid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "category_name",
                    models.CharField(max_length=100, verbose_name="Название категории"),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True, null=True, unique=True, verbose_name="URL-адрес"
                    ),
                ),
                (
                    "category_image",
                    models.ImageField(
                        storage=products.storage.OverwriteStorage(),
                        upload_to="categories",
                        verbose_name="Изображение категории",
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Порядок отображения"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активна"),
                ),
            ],
            options={
                "verbose_name": "Автомобильная категория",
                "verbose_name_plural": "Автомобильные категории",
                "db_table": "products_category",
                "ordering": ["display_order", "category_name"],
            },
        ),
        migrations.CreateModel(
            name="Coupon",
            fields=[
                (
                    "uid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "coupon_code",
                    models.CharField(max_length=10, verbose_name="Код купона"),
                ),
                (
                    "is_expired",
                    models.BooleanField(default=False, verbose_name="Истёк"),
                ),
                (
                    "discount_amount",
                    models.IntegerField(default=100, verbose_name="Сумма скидки"),
                ),
                (
                    "minimum_amount",
                    models.IntegerField(
                        default=500, verbose_name="Минимальная сумма заказа"
                    ),
                ),
            ],
            options={
                "verbose_name": "Купон",
                "verbose_name_plural": "Купоны",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="KitVariant",
            fields=[
                (
                    "uid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "name",
                    models.CharField(
                        max_length=100, verbose_name="Название комплектации"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Символьный код"
                    ),
                ),
                (
                    "price_modifier",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Модификатор цены",
                    ),
                ),
                (
                    "order",
                    models.IntegerField(default=0, verbose_name="Порядок сортировки"),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="configurations",
                        verbose_name="Изображение схемы",
                    ),
                ),
                (
                    "is_option",
                    models.BooleanField(
                        default=False, verbose_name="Дополнительная опция"
                    ),
                ),
            ],
            options={
                "verbose_name": "Тип комплектации",
                "verbose_name_plural": "Типы комплектаций",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "uid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
                ("product_name", models.CharField(max_length=200)),
                ("slug", models.SlugField(unique=True)),
                ("price", models.IntegerField()),
                ("product_desription", django_ckeditor_5.fields.CKEditor5Field()),
                ("newest_product", models.BooleanField(default=False)),
                ("product_sku", models.CharField(max_length=50, unique=True)),
                ("page_title", models.CharField(blank=True, max_length=200)),
                ("meta_description", models.TextField(blank=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="products.category",
                        verbose_name="Категория",
                    ),
                ),
            ],
            options={
                "verbose_name": "Автомобильный товар",
                "verbose_name_plural": "Автомобильные товары",
                "db_table": "products_product",
                "ordering": ["-created_at", "product_name"],
            },
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "uid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "image",
                    models.ImageField(
                        help_text="Файл сохранится с точным именем без хеш-суффиксов",
                        storage=products.storage.OverwriteStorage(),
                        upload_to="product",
                        verbose_name="Изображение",
                    ),
                ),
                (
                    "is_main",
                    models.BooleanField(
                        default=False,
                        help_text="Отображается в каталоге и как основное в карточке товара",
                        verbose_name="Главное изображение",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_images",
                        to="products.product",
                        verbose_name="Товар",
                    ),
                ),
            ],
            options={
                "verbose_name": "Изображение товара",
                "verbose_name_plural": "Изображения товаров",
                "ordering": ["created_at"],
            },
        ),
    ]
