# Generated by Django 5.1.4 on 2025-07-19 07:02

import django.db.models.deletion
import products.storage
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ['created_at'], 'verbose_name': 'Изображение товара', 'verbose_name_plural': 'Изображения товаров'},
        ),
        migrations.AddField(
            model_name='category',
            name='category_type',
            field=models.CharField(choices=[('cars', 'Автомобили'), ('boats', 'Лодки')], default='cars', help_text='Автомобили или лодки для правильной обработки', max_length=20, verbose_name='Тип категории'),
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Для создания иерархии: Лодки → Hunter, Marlin...', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='products.category', verbose_name='Родительская категория'),
        ),
        migrations.AddField(
            model_name='product',
            name='boat_mat_length',
            field=models.PositiveIntegerField(blank=True, help_text='Длина коврика для лодки в сантиметрах', null=True, verbose_name='Длина коврика (см)'),
        ),
        migrations.AddField(
            model_name='product',
            name='boat_mat_width',
            field=models.PositiveIntegerField(blank=True, help_text='Ширина коврика для лодки в сантиметрах', null=True, verbose_name='Ширина коврика (см)'),
        ),
        migrations.AlterField(
            model_name='color',
            name='border_image',
            field=models.ImageField(blank=True, help_text='Для визуализации окантовки этого цвета', null=True, storage=products.storage.OverwriteStorage(), upload_to='colors/border', verbose_name='Изображение окантовки'),
        ),
        migrations.AlterField(
            model_name='color',
            name='carpet_image',
            field=models.ImageField(blank=True, help_text='Для визуализации коврика этого цвета', null=True, storage=products.storage.OverwriteStorage(), upload_to='colors/carpet', verbose_name='Изображение коврика'),
        ),
        migrations.AlterField(
            model_name='color',
            name='color_type',
            field=models.CharField(choices=[('carpet', 'Коврик'), ('border', 'Окантовка')], default='carpet', max_length=10, verbose_name='Тип цвета'),
        ),
        migrations.AlterField(
            model_name='color',
            name='hex_code',
            field=models.CharField(help_text='Цветовой код в формате #RRGGBB', max_length=7, verbose_name='HEX-код'),
        ),
        migrations.AlterUniqueTogether(
            name='wishlist',
            unique_together={('user', 'product', 'kit_variant', 'carpet_color', 'border_color', 'has_podpyatnik')},
        ),
    ]
