# Generated by Django 5.1.4 on 2025-05-15 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_add_configuration_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configurationtype',
            name='image',
        ),
        migrations.AddField(
            model_name='configurationtype',
            name='scheme_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/schema', verbose_name='Изображение схемы'),
        ),
        migrations.AlterField(
            model_name='configurationtype',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки'),
        ),
    ]
