# Generated by Django 5.1.4 on 2025-05-15 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_remove_configurationtype_image_and_more'),
        ('products', '0019_rename_sizevariant_to_kitvariant'),
    ]

    operations = [
    ]
