# Generated by Django 5.1.4 on 2025-05-18 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_kitvariant_is_option_and_podpyatnik'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConfigurationType',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='size_variant',
        ),
        migrations.RemoveField(
            model_name='product',
            name='size_variant',
        ),
        migrations.RemoveField(
            model_name='product',
            name='kit_variant',
        ),
        migrations.AddField(
            model_name='color',
            name='color_type',
            field=models.CharField(choices=[('carpet', 'Коврик'), ('border', 'Окантовка')], default='carpet', max_length=10, verbose_name='Тип применения'),
        ),
        migrations.AddField(
            model_name='color',
            name='image_file',
            field=models.CharField(blank=True, max_length=100, verbose_name='Файл изображения'),
        ),
        migrations.AddField(
            model_name='color',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='Доступен для заказа'),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='border_color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wishlist_border_items', to='products.color'),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='carpet_color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wishlist_carpet_items', to='products.color'),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='has_podpyatnik',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='kitvariant',
            name='code',
            field=models.CharField(max_length=50, unique=True, verbose_name='Символьный код'),
        ),
        migrations.DeleteModel(
            name='SizeVariant',
        ),
    ]
