# Generated by Django 5.1.4 on 2025-05-25 08:59

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_alter_category_options_alter_colorvariant_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='color',
            options={'ordering': ['color_type', 'display_order', 'name'], 'verbose_name': 'Цвет', 'verbose_name_plural': 'Цвета'},
        ),
        migrations.AlterModelOptions(
            name='coupon',
            options={'ordering': ['-created_at'], 'verbose_name': 'Купон', 'verbose_name_plural': 'Купоны'},
        ),
        migrations.AlterModelOptions(
            name='kitvariant',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Тип комплектации', 'verbose_name_plural': 'Типы комплектаций'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at', 'product_name'], 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ['created_at'], 'verbose_name': 'Изображение товара', 'verbose_name_plural': 'Изображения товаров'},
        ),
        migrations.AlterModelOptions(
            name='productreview',
            options={'ordering': ['-date_added'], 'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
        migrations.AlterModelOptions(
            name='wishlist',
            options={'ordering': ['-added_on'], 'verbose_name': 'Избранное', 'verbose_name_plural': 'Избранное'},
        ),
        migrations.AlterUniqueTogether(
            name='productreview',
            unique_together={('user', 'product')},
        ),
    ]
