# Generated by Django 5.1.4 on 2025-05-26 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_alter_color_options_alter_coupon_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ColorVariant',
        ),
        migrations.RemoveField(
            model_name='product',
            name='parent',
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Базовая цена'),
        ),
    ]
