# Generated by Django 5.1.4 on 2025-05-27 18:42
# ✅ ИСПРАВЛЕНО: Заменен импорт django_summernote на ckeditor

# ❌ СТАРЫЙ ИМПОРТ: import django_summernote.fields
import ckeditor.fields  # ✅ НОВЫЙ ИМПОРТ
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0025_delete_colorvariant_remove_product_parent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_desription',
            # ✅ ИСПРАВЛЕНО: Заменен django_summernote.fields на ckeditor.fields
            field=ckeditor.fields.RichTextField(
                help_text='Подробное описание товара с возможностью форматирования',
                verbose_name='Описание товара'
            ),
        ),
    ]