# Generated by Django 5.1.4 on 2025-05-27 18:42

import django_summernote.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0025_delete_colorvariant_remove_product_parent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_desription',
            field=django_summernote.fields.SummernoteTextField(help_text='Подробное описание товара с возможностью форматирования', verbose_name='Описание товара'),
        ),
    ]
