# Generated by Django 5.1.4 on 2025-06-03 09:14

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0026_alter_product_product_desription'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['display_order', 'category_name'], 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AddField(
            model_name='category',
            name='additional_content',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Дополнительная информация, советы, руководства по выбору', null=True, verbose_name='Дополнительный контент'),
        ),
        migrations.AddField(
            model_name='category',
            name='category_sku',
            field=models.PositiveIntegerField(blank=True, help_text='Уникальный номер для импорта/экспорта', null=True, unique=True, verbose_name='SKU категории'),
        ),
        migrations.AddField(
            model_name='category',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Основное описание категории для отображения на странице', null=True, verbose_name='Описание категории'),
        ),
        migrations.AddField(
            model_name='category',
            name='display_order',
            field=models.PositiveIntegerField(default=0, help_text='Чем меньше число, тем выше в списке', verbose_name='Порядок отображения'),
        ),
        migrations.AddField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Неактивные категории не отображаются на сайте', verbose_name='Активна'),
        ),
        migrations.AddField(
            model_name='category',
            name='meta_description',
            field=models.TextField(blank=True, help_text='Description для поисковиков (макс. 160 символов)', max_length=160, null=True, verbose_name='SEO описание'),
        ),
        migrations.AddField(
            model_name='category',
            name='meta_title',
            field=models.CharField(blank=True, help_text='Title для поисковиков (макс. 60 символов)', max_length=60, null=True, verbose_name='SEO заголовок'),
        ),
        migrations.AddField(
            model_name='category',
            name='page_title',
            field=models.CharField(blank=True, help_text='H1 заголовок на странице категории', max_length=100, null=True, verbose_name='Заголовок страницы'),
        ),
        migrations.AddField(
            model_name='product',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='products.product'),
        ),
    ]
