# Generated by Django 5.1.4 on 2025-06-06 11:26

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0027_alter_category_options_category_additional_content_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='parent',
        ),
        migrations.AlterField(
            model_name='category',
            name='additional_content',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Вставьте ссылку на YouTube видео (автоматически преобразуется в плеер)', null=True, verbose_name='Дополнительный контент'),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_image',
            field=models.ImageField(help_text='Рекомендуемый размер: 800x400 px', upload_to='categories', verbose_name='Изображение категории'),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(help_text='Основное название категории для отображения', max_length=100, verbose_name='Название категории'),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_sku',
            field=models.PositiveIntegerField(blank=True, help_text='Уникальный номер для внутреннего учета', null=True, unique=True, verbose_name='Артикул категории'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Основное описание категории с форматированием', null=True, verbose_name='Описание категории'),
        ),
        migrations.AlterField(
            model_name='category',
            name='display_order',
            field=models.PositiveIntegerField(default=0, help_text='Чем меньше число, тем выше в списке (0 = сверху)', verbose_name='Порядок отображения'),
        ),
        migrations.AlterField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Отображать категорию на сайте', verbose_name='Активна'),
        ),
        migrations.AlterField(
            model_name='category',
            name='meta_description',
            field=models.TextField(blank=True, help_text='Описание для поисковых систем (до 160 символов)', max_length=160, null=True, verbose_name='Meta Description'),
        ),
        migrations.AlterField(
            model_name='category',
            name='meta_title',
            field=models.CharField(blank=True, help_text='Заголовок для поисковых систем (до 60 символов)', max_length=60, null=True, verbose_name='Meta Title'),
        ),
        migrations.AlterField(
            model_name='category',
            name='page_title',
            field=models.CharField(blank=True, help_text='Основной заголовок на странице категории (до 70 символов)', max_length=70, null=True, verbose_name='Заголовок страницы (H1)'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, help_text='Автоматически генерируется из названия', null=True, unique=True, verbose_name='URL-адрес'),
        ),
    ]
