# Generated by Django 5.1.4 on 2025-06-09 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0028_remove_product_parent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='additional_content',
            field=models.TextField(blank=True, help_text='Вставьте ссылку на YouTube видео или готовый HTML-код. YouTube ссылки автоматически преобразуются в плеер', null=True, verbose_name='Дополнительный контент'),
        ),
    ]
